# Copyright (c) 2026 SurfHost.nl
# SPDX-License-Identifier: MIT

PLUGIN_NAME=		openvpn-auth-oauth2
PLUGIN_VERSION=		1.1
PLUGIN_COMMENT=		OpenVPN SSO via OpenID Connect (Microsoft Entra ID and others)
PLUGIN_DEPENDS=		openvpn-auth-oauth2
PLUGIN_LICENSE=		MIT
PLUGIN_MAINTAINER=	hans@surfhost.nl
PLUGIN_WWW=		https://github.com/SurfHost/opnsense-plugin-entra-sso

# When this directory is dropped into an opnsense/plugins checkout under
# security/, the standard include below applies unchanged.
.include "../../Mk/plugins.mk"
