[start]
command:/usr/local/etc/rc.d/openvpnauthoauth2 start
parameters:
type:script
message:starting openvpn-auth-oauth2

[stop]
command:/usr/local/etc/rc.d/openvpnauthoauth2 stop
parameters:
type:script
message:stopping openvpn-auth-oauth2

[restart]
command:/usr/local/etc/rc.d/openvpnauthoauth2 restart
parameters:
type:script
message:restarting openvpn-auth-oauth2

[status]
command:/usr/local/etc/rc.d/openvpnauthoauth2 status; exit 0
parameters:
type:script_output
message:request openvpn-auth-oauth2 status

[details]
command:/usr/local/opnsense/scripts/OPNsense/OpenVPNAuthOAuth2/status.py; exit 0
parameters:
type:script_output
message:request openvpn-auth-oauth2 details
